# Generated by Django 4.2 on 2023-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_api', '0002_alter_plants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('family', models.CharField(default='Unknown', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
