# Generated by Django 4.2 on 2023-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_api', '0003_plant_delete_plants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='family',
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
