# Generated by Django 4.2 on 2023-04-17 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur_api', '0006_alter_plant_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
