# Generated by Django 4.2 on 2023-04-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleur_api', '0002_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
    ]
