# Generated by Django 4.2 on 2023-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur_api', '0003_remove_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
