# Generated by Django 4.2 on 2023-04-13 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleur_api', '0004_plant_image_plant_notes_alter_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='notes',
        ),
        migrations.AddField(
            model_name='plant',
            name='header',
            field=models.CharField(default='Header', max_length=32),
        ),
        migrations.AddField(
            model_name='plant',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleur_api.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
