# Generated by Django 4.2 on 2023-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur_api', '0005_remove_plant_name_remove_plant_notes_plant_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='header',
            field=models.CharField(default='', max_length=32),
        ),
    ]
