# Generated by Django 4.2 on 2023-04-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleur_api', '0006_alter_plant_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
